services:
  oceancraft-next:
    container_name: oceancraft-next
    restart: always
    image: node:20.11.1
    ports:
      - 4001:3000
    environment:
      - PORT=3000

    volumes:
      - ./:/usr/src/oceancraft-next
    working_dir: /usr/src/oceancraft-next

    networks:
      - client-network

    # FOR PRODUCTION
    command: bash -c "yarn  && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge
